# Generated by Django 4.1.2 on 2022-12-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textbook_exchange", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friendrequest", old_name="sender", new_name="user1",
        ),
        migrations.RenameField(
            model_name="friendrequest",
            old_name="receiver_confirm",
            new_name="user1_confirm",
        ),
        migrations.RenameField(
            model_name="friendrequest", old_name="receiver", new_name="user2",
        ),
        migrations.RenameField(
            model_name="friendrequest",
            old_name="sender_confirm",
            new_name="user2_confirm",
        ),
    ]
