# Generated by Django 4.1.2 on 2022-12-06 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "textbook_exchange",
            "0003_alter_friendrequest_user1_alter_friendrequest_user2",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="friendrequest", name="user1",),
        migrations.RemoveField(model_name="friendrequest", name="user1_confirm",),
        migrations.RemoveField(model_name="friendrequest", name="user2",),
        migrations.RemoveField(model_name="friendrequest", name="user2_confirm",),
        migrations.AddField(
            model_name="friendrequest",
            name="receiver",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="sender",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
